export const MEMEWAR_ADDRESS = "0x674896Dea26aa6FDC6bA5CCa486C8AE300b95BCF"

export const MEMEWAR_ABI = [
  {"inputs":[],"stateMutability":"nonpayable","type":"constructor"},
  {"inputs":[{"internalType":"uint256","name":"memeWarId","type":"uint256","indexed":true}],"type":"event","name":"MemeWarCancelled","anonymous":false},
  {"inputs":[{"internalType":"uint256","name":"id","type":"uint256","indexed":true},{"internalType":"address","name":"creator","type":"address","indexed":true},{"internalType":"string","name":"title","type":"string","indexed":false},{"internalType":"uint256","name":"deadline","type":"uint256","indexed":false}],"type":"event","name":"MemeWarCreated","anonymous":false},
  {"inputs":[{"internalType":"uint256","name":"memeWarId","type":"uint256","indexed":true},{"internalType":"enum MemeWar.Side","name":"winningSide","type":"uint8","indexed":false},{"internalType":"uint256","name":"prizePool","type":"uint256","indexed":false}],"type":"event","name":"MemeWarResolved","anonymous":false},
  {"inputs":[{"internalType":"uint256","name":"memeWarId","type":"uint256","indexed":true},{"internalType":"address","name":"staker","type":"address","indexed":true},{"internalType":"enum MemeWar.Side","name":"side","type":"uint8","indexed":false},{"internalType":"uint256","name":"amount","type":"uint256","indexed":false}],"type":"event","name":"Staked","anonymous":false},
  {"inputs":[{"internalType":"uint256","name":"memeWarId","type":"uint256","indexed":true},{"internalType":"address","name":"winner","type":"address","indexed":true},{"internalType":"uint256","name":"amount","type":"uint256","indexed":false}],"type":"event","name":"WinningsClaimed","anonymous":false},
  {"inputs":[],"stateMutability":"view","type":"function","name":"MAX_STAKE","outputs":[{"internalType":"uint256","name":"","type":"uint256"}]},
  {"inputs":[],"stateMutability":"view","type":"function","name":"PLATFORM_FEE_BPS","outputs":[{"internalType":"uint256","name":"","type":"uint256"}]},
  {"inputs":[{"internalType":"uint256","name":"memeWarId","type":"uint256"}],"stateMutability":"nonpayable","type":"function","name":"cancelMemeWar"},
  {"inputs":[{"internalType":"uint256","name":"memeWarId","type":"uint256"}],"stateMutability":"nonpayable","type":"function","name":"claimWinnings"},
  {"inputs":[{"internalType":"uint256","name":"","type":"uint256"},{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function","name":"claimed","outputs":[{"internalType":"bool","name":"","type":"bool"}]},
  {"inputs":[{"internalType":"string","name":"title","type":"string"},{"internalType":"bytes32","name":"memeHash","type":"bytes32"},{"internalType":"uint256","name":"durationInSeconds","type":"uint256"}],"stateMutability":"nonpayable","type":"function","name":"createMemeWar","outputs":[{"internalType":"uint256","name":"","type":"uint256"}]},
  {"inputs":[{"internalType":"uint256","name":"memeWarId","type":"uint256"}],"stateMutability":"view","type":"function","name":"getMemeWar","outputs":[{"internalType":"struct MemeWar.MemeWarData","name":"","type":"tuple","components":[{"internalType":"address","name":"creator","type":"address"},{"internalType":"string","name":"title","type":"string"},{"internalType":"bytes32","name":"memeHash","type":"bytes32"},{"internalType":"uint256","name":"deadline","type":"uint256"},{"internalType":"uint256","name":"stakeOnBelieve","type":"uint256"},{"internalType":"uint256","name":"stakeOnSkeptic","type":"uint256"},{"internalType":"uint8","name":"winningSide","type":"uint8"},{"internalType":"uint8","name":"status","type":"uint8"}]}]},
  {"inputs":[{"internalType":"uint256","name":"memeWarId","type":"uint256"},{"internalType":"address","name":"user","type":"address"}],"stateMutability":"view","type":"function","name":"getStakeInfo","outputs":[{"internalType":"struct MemeWar.StakeInfo","name":"","type":"tuple","components":[{"internalType":"bool","name":"hasStaked","type":"bool"},{"internalType":"uint8","name":"side","type":"uint8"},{"internalType":"uint256","name":"amount","type":"uint256"}]}]},
  {"inputs":[{"internalType":"uint256","name":"memeWarId","type":"uint256"}],"stateMutability":"view","type":"function","name":"getTotalStakers","outputs":[{"internalType":"uint256","name":"believersCount","type":"uint256"},{"internalType":"uint256","name":"skepticsCount","type":"uint256"}]},
  {"inputs":[],"stateMutability":"view","type":"function","name":"memeWarCount","outputs":[{"internalType":"uint256","name":"","type":"uint256"}]},
  {"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function","name":"memeWars","outputs":[{"internalType":"address","name":"creator","type":"address"},{"internalType":"string","name":"title","type":"string"},{"internalType":"bytes32","name":"memeHash","type":"bytes32"},{"internalType":"uint256","name":"deadline","type":"uint256"},{"internalType":"uint256","name":"stakeOnBelieve","type":"uint256"},{"internalType":"uint256","name":"stakeOnSkeptic","type":"uint256"},{"internalType":"uint8","name":"winningSide","type":"uint8"},{"internalType":"uint8","name":"status","type":"uint8"}]},
  {"inputs":[],"stateMutability":"view","type":"function","name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}]},
  {"inputs":[{"internalType":"uint256","name":"memeWarId","type":"uint256"},{"internalType":"uint8","name":"winner","type":"uint8"}],"stateMutability":"nonpayable","type":"function","name":"resolveMemeWar"},
  {"inputs":[{"internalType":"uint256","name":"memeWarId","type":"uint256"},{"internalType":"uint8","name":"side","type":"uint8"}],"stateMutability":"payable","type":"function","name":"stakeOnSide"},
  {"inputs":[{"internalType":"uint256","name":"","type":"uint256"},{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function","name":"stakes","outputs":[{"internalType":"bool","name":"hasStaked","type":"bool"},{"internalType":"uint8","name":"side","type":"uint8"},{"internalType":"uint256","name":"amount","type":"uint256"}]},
  {"stateMutability":"payable","type":"receive"}
]
